### PR TITLE
Resolves issues with array map custom prop

### LINKED ISSUE #591: 🐞 Components that use array map custom prop are not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The data does not change at all

### Error message

_No response_

### Screenshots

_No response_

### Expected Behavior

_No response_

### System configuration

```markdown
1. OS:
2. Bits:
3. Browser:
4. Atri framework version:
5. Virtual environment:
```

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jonathanalvares9009**
## Reference
Add reference to a related issue that this pull request is addressing. For example, fixes #591

## Describe the pull request

Please describe the changes proposed in this pull request.

## Contributors (in case of a commit with multiple authors)

Co-authors:

### CODE REVIEW

File: packages/canvas-runtime-utils/src/utils.ts [hunk 1]
```diff
@@ -162,70 +162,52 @@ export function getStylesAlias(id: string, componentTree: Tree, cssTree: Tree) {
...
+      newObj[key] = {};
+    }
+    newObj[key] = createObject(newObj[key], remainingKeys, value);
+  } else if (typeof key === "number") {
+    // If the key is a number, it refers to an array element
+    if (!Array.isArray(newObj)) {
+      throw new Error("Cannot access element of non-array");
+    }
+    // If the key is 0 (first element) or equal to the length of the array (last element), set the value at the specified location in the array
+    if ((key === 0 || key === newObj.length) && selector.length == 1) {
```
Comment (cruxcode) [inline packages/canvas-runtime-utils/src/utils.ts:200]: The condition `(key === 0 || key === newObj.length)` should be `key <= newObj.length`, right?

Comment (jonathanalvares9009) [reply packages/canvas-runtime-utils/src/utils.ts:200]: No sir, not really this condition gets triggered when the array is completely empty or when a new element is pushed into the array. If an array is being patched it will not run

Comment (cruxcode) [reply packages/canvas-runtime-utils/src/utils.ts:200]: Does this mean, that we don't need to use `createObject()` if we are patching an array?

Comment (jonathanalvares9009) [reply packages/canvas-runtime-utils/src/utils.ts:200]: No, we use it. But if the array is empty or something is being pushed them it will created an element at the index with the value else it will just put the value at the specified index

Comment (cruxcode) [reply packages/canvas-runtime-utils/src/utils.ts:200]: In the case of the patch, we expect that the value is an array. Did I understand it correctly?

Comment (cruxcode) [reply packages/canvas-runtime-utils/src/utils.ts:200]: Please point me to the lines where we are handling these two cases respectively.

File: packages/canvas-runtime-utils/src/utils.ts [hunk 2]
```diff
@@ -162,70 +162,52 @@ export function getStylesAlias(id: string, componentTree: Tree, cssTree: Tree) {
...
+      newObj[key] = value;
```
Comment (jonathanalvares9009) [inline packages/canvas-runtime-utils/src/utils.ts:201]: So on this line it will create a new element with the value

File: packages/canvas-runtime-utils/src/utils.ts [hunk 3]
```diff
@@ -162,70 +162,52 @@ export function getStylesAlias(id: string, componentTree: Tree, cssTree: Tree) {
...
-      // recursively write the object
-      referenceObject[key] = createObject(
-        typeof referenceObject[key] === "undefined" ? {} : referenceObject[key],
-        remainingKeys,
-        value
-      );
+      if (key > newObj.length) {
+        throw new Error("Array index out of bounds");
+      }
+      newObj[key] = createObject(newObj[key], remainingKeys, value);
```
Comment (jonathanalvares9009) [inline packages/canvas-runtime-utils/src/utils.ts:206]: This line will replace the old value with the new value if the index is already present

Comment (cruxcode) [reply packages/canvas-runtime-utils/src/utils.ts:206]: By reading the code, it seems like this won't be able to handle the case where we are changing an entry in between the array. It will throw an error because the recursive call to `createObject()` in this line will be passed an empty `remainingKeys` array. This will lead to an undefined `key` in this call.

Comment (jonathanalvares9009) [reply packages/canvas-runtime-utils/src/utils.ts:206]: If the key is undefined it will return the value so it finally gets patched

File: packages/canvas-runtime-utils/src/utils.ts [hunk 4]
```diff
@@ -162,70 +162,52 @@ export function getStylesAlias(id: string, componentTree: Tree, cssTree: Tree) {
...
+  if (referenceObj === null || referenceObj === undefined) {
+    throw new Error("Cannot patch a null or undefined object");
   }
-  if (keys.length === 0) {
+
+  // Create a copy of the object
+  const newObj = JSON.parse(JSON.stringify(referenceObj));
+
+  // Base case: if the selector array is empty, set the value of the new object to the given value
+  if (selector.length === 0) {
```
Comment (jonathanalvares9009) [inline packages/canvas-runtime-utils/src/utils.ts:178]: It checks on this line if the selector array is empty it means we have traversed to the exact property that is to be patched so I return the value

File: packages/canvas-runtime-utils/src/utils.ts (hunk 3 above)
Comment (cruxcode) [reply packages/canvas-runtime-utils/src/utils.ts:206]: Are you sure we won't hit the else condition in line 208?

Comment (jonathanalvares9009) [reply packages/canvas-runtime-utils/src/utils.ts:206]: We will hit the condition in line 208 only if we pass an object in the selector array, or a nested array basically anything other than a string or a number. As it checks on line 178 if the selector array is empty, if it is it will return the value and will not proceed to the line where it extracts the key from the selector array
